---
apiVersion: eks.amazonaws.com/v1
kind: TargetGroupBinding
metadata:
  name: rosa-regional-frontend
  namespace: rosa-regional-frontend
spec:
  serviceRef:
    name: rosa-regional-frontend
    port: 8000
  targetGroupARN: TARGET_GROUP_ARN  # Replace with actual ARN or use Helm chart with ConfigMap lookup
  targetType: ip
